kafka:
  enabled: true
redis:
  enabled: true
vault:
  enabled: true

apiGateway:
  replicaCount: 2
  image: kraionyx/api-gateway:latest
  port: 8080

fhirAdapter:
  replicaCount: 2
  image: kraionyx/fhir-adapter:latest
  port: 8080

clinicalNlp:
  replicaCount: 2
  image: kraionyx/clinical-nlp:latest
  port: 8080

sttEngine:
  replicaCount: 2
  image: kraionyx/stt-engine:latest
  port: 8080

audioProcessor:
  replicaCount: 2
  image: kraionyx/audio-processor:latest
  port: 8080
